services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    # image: postgres:latest
    container_name: postgres
    env_file: .env
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - psqldata:/var/lib/postgresql/data
    networks:
      - app

  airflow:
    # build:
    #   context: ./airflow
    #   dockerfile: ./Dockerfile
    image: apache/airflow:3.1.0-python3.13
    container_name: airflow
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: ["standalone"]
    networks:
      - app
  # superset:

volumes:
  psqldata:

networks:
  app:
    driver: bridge