services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    container_name: postgres
    env_file: .env
    volumes:
      - psqldata:/var/lib/postgresql/data
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:latest
    container_name: airflow
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: >
      bash -c "
        echo '🔧 Ajustando permissões...';
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins &&
        chown -R airflow:root /opt/airflow &&
        chmod -R 775 /opt/airflow &&
        echo '✅ Permissões ajustadas. Iniciando Airflow...' &&
        exec airflow standalone
      "
    networks:
      - app

  superset:
    build:
      context: ./superset
      dockerfile: ./Dockerfile
    container_name: superset
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8088:8088"
    networks:
      - app

volumes:
  psqldata:

networks:
  app:
    driver: bridge
