services:
  postgres:
    # build:
    #   context: ./postgres
    #   dockerfile: ./Dockerfile
    image: postgres:latest
    container_name: postgres
    env_file: .env
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - psqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    # airflow:
    # superset:

volumes:
  psqldata: